ekf_node:
  ros__parameters:
    frequency: 30
    sensor_timeout: 0.1

    odom0: /odom
    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  true,  true,  true]
    imu0_queue_size: 10
    imu0_differential: false

    use_sim_time: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
