rtabmap:
  ros__parameters:
    frame_id: "base_footprint_link"
    use_sim_time: true
    subscribe_depth: false
    subscribe_scan: false
    subscribe_scan_cloud: true
    qos_image: 2
    qos_imu: 2
    qos_scan_cloud: 2
    Reg/Force3DoF: true
    RGBD/Enabled: false
    approx_sync: true
    sync_queue_size: 20
    topic_queue_size: 20

